/* TuringParser.java */
/* Generated By:JavaCC: Do not edit this line. TuringParser.java */
import java.util.*;

public class TuringParser implements TuringParserConstants {

    public List<CompilerError> errors = new ArrayList<>();

    public static class CompilerError {
        String type;
        String message;
        int line;
        int column;

        public CompilerError(String type, String message, int line, int column) {
            this.type = type;
            this.message = message;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            // Se ajustó la puntuación para coincidir con tu formato exacto
            return "Error " + type + " en " + line + "," + column + ". " + message;
        }
    }

    private void reportError(String type, String message, Token t) {
        errors.add(new CompilerError(type, message, t.beginLine, t.beginColumn));
    }

    public static void main(String[] args) {
        try {
            java.io.InputStream in;

            if (args.length == 1) {
                System.out.println("Leyendo archivo: " + args[0]);
                in = new java.io.FileInputStream(args[0]);
            } else {
                System.out.println("Leyendo desde consola...");
                in = System.in;
            }

            TuringParser parser = new TuringParser(in);
            parser.Program();

            System.out.println("\n--------------------------------");

            if (parser.errors.isEmpty()) {
                System.out.println("\u2714 COMPILACI\u00d3N EXITOSA (0 errores)");
            } else {
                System.out.println("\u2716 SE ENCONTRARON " + parser.errors.size() + " ERRORES:");
                for (CompilerError e : parser.errors) {
                    System.out.println(e);
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /* ================= RECUPERACIÓN ================= */

    void recover(int... syncTokens) {
        Token t = getToken(1);

        if (t.kind == EOF || isKind(t.kind, syncTokens)) return;

        while (true) {
            getNextToken();
            t = getToken(1);
            if (t.kind == EOF || isKind(t.kind, syncTokens)) break;
        }
    }

    boolean isKind(int kind, int[] kinds) {
        for (int k : kinds) if (k == kind) return true;
        return false;
    }

    void error_skip_config() {
        Token t = getToken(1);

        while (t.kind != EOF &&
               t.kind != STATES &&
               t.kind != SYMBOLS &&
               t.kind != START &&
               t.kind != BLANK &&
               t.kind != FINALS &&
               t.kind != RBRACE) {

            getNextToken();
            t = getToken(1);
        }
    }

/* ================= SINTÁCTICO ================= */
  final public 
void Program() throws ParseException {
    try {
      jj_consume_token(MACHINE);
      jj_consume_token(NAME);
      jj_consume_token(COLON);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Se esperaba la palabra reservada \"machine\" seguida de un nombre (ID) seguido de '{'.",
                t
            );
        }

        recover(CONFIG, STATE);
    }
    ConfigBlock();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STATE:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      StateBlock();
    }
    try {
      jj_consume_token(END);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Cierra la declaraci\u00f3n con la palabra reservada 'end'",
                t
            );
        }
    }
    jj_consume_token(0);
}

  final public void ConfigBlock() throws ParseException {
    try {
      jj_consume_token(CONFIG);
      jj_consume_token(LBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar el bloque de definici\u00f3n. Se esperaba la palabra reservada \"config\" seguido de {",
                t
            );
        }

        recover(STATES, SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }
    ConfigEntry();
    try {
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Necesitas cerrar el bloque con \"}\"",
                t
            );
        }

        recover(STATE, END);
    }
}

  final public void ConfigEntry() throws ParseException {
    try {
      jj_consume_token(STATES);
      jj_consume_token(COLON);
      IdList();
      jj_consume_token(COMMA);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba una declaraci\u00f3n de los estados de la maquina. Revisa la sintaxis",
                t
            );
        }

        recover(SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(SYMBOLS);
      jj_consume_token(COLON);
      SymbolsList();
      jj_consume_token(COMMA);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba una declaraci\u00f3n de los simbolos de cinta. Revisa la sintaxis",
                t
            );
        }

        recover(START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(START);
      jj_consume_token(COLON);
      jj_consume_token(ID);
      jj_consume_token(COMMA);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n del estado inicial. Revisa la sintaxis",
                t
            );
        }

        recover(BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(BLANK);
      jj_consume_token(COLON);
      jj_consume_token(SYMBOL);
      jj_consume_token(COMMA);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n del simbolo blanco. Revisa la sintaxis",
                t
            );
        }

        recover(FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(FINALS);
      jj_consume_token(COLON);
      IdList();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n de los estados finales. Revisa la sintaxis",
                t
            );
        }

        recover(RBRACE, STATE, END);
    }
}

  final public void StateBlock() throws ParseException {
    try {
      jj_consume_token(STATE);
      jj_consume_token(ID);
      jj_consume_token(PRODUCE);
      label_2:
      while (true) {
        TransitionBlock();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ON:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n de transici\u00f3n. Usa la palabra reservada 'state' y el identificador adecuado",
                t
            );
        }

        recover(STATE, END);
    }
}

  final public void TransitionBlock() throws ParseException {
    try {
      jj_consume_token(ON);
      jj_consume_token(SYMBOL);
      jj_consume_token(COLON);
      jj_consume_token(LBRACE);
      jj_consume_token(WRITE);
      jj_consume_token(COLON);
      jj_consume_token(SYMBOL);
      jj_consume_token(COMMA);
      jj_consume_token(MOVE);
      jj_consume_token(COLON);
      jj_consume_token(DIR);
      jj_consume_token(COMMA);
      jj_consume_token(NEXT);
      jj_consume_token(COLON);
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1ido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la transici\u00f3n. Revisa la documentaci\u00f3n",
                t
            );
        }

        recover(SEMICOLON, END);
    }
}

  final public void IdList() throws ParseException {
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      jj_consume_token(ID);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        jj_consume_token(ID);
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
}

  final public void SymbolsList() throws ParseException {
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYMBOL:{
      jj_consume_token(SYMBOL);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        jj_consume_token(SYMBOL);
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
}

  /** Generated Token Manager. */
  public TuringParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2000,0x2000000,0x4000,0x2000000,0x2000000,0x20000000,0x2000000,0x100000,};
	}

  /** Constructor with InputStream. */
  public TuringParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TuringParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new TuringParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TuringParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new TuringParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new TuringParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TuringParser(TuringParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TuringParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[32];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 8; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 32; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
