/* Generated By:JavaCC: Do not edit this line. TuringParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TuringParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MACHINE = 6;
  /** RegularExpression Id. */
  int CONFIG = 7;
  /** RegularExpression Id. */
  int STATES = 8;
  /** RegularExpression Id. */
  int SYMBOLS = 9;
  /** RegularExpression Id. */
  int START = 10;
  /** RegularExpression Id. */
  int BLANK = 11;
  /** RegularExpression Id. */
  int FINALS = 12;
  /** RegularExpression Id. */
  int STATE = 13;
  /** RegularExpression Id. */
  int ON = 14;
  /** RegularExpression Id. */
  int WRITE = 15;
  /** RegularExpression Id. */
  int MOVE = 16;
  /** RegularExpression Id. */
  int NEXT = 17;
  /** RegularExpression Id. */
  int DIR = 18;
  /** RegularExpression Id. */
  int SYMBOL = 19;
  /** RegularExpression Id. */
  int LBRACE = 20;
  /** RegularExpression Id. */
  int RBRACE = 21;
  /** RegularExpression Id. */
  int LBRACKET = 22;
  /** RegularExpression Id. */
  int RBRACKET = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int NAME = 27;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"machine\"",
    "\"config\"",
    "\"states\"",
    "\"symbols\"",
    "\"start\"",
    "\"blank\"",
    "\"finals\"",
    "\"state\"",
    "\"on\"",
    "\"write\"",
    "\"move\"",
    "\"next\"",
    "<DIR>",
    "<SYMBOL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "<ID>",
    "<NAME>",
    "<UNEXPECTED_CHAR>",
  };

}
