/* TuringParser.java */
/* Generated By:JavaCC: Do not edit this line. TuringParser.java */
import java.util.*;
import java.io.PrintWriter;
import java.io.FileWriter;
import java.io.IOException;

public class TuringParser implements TuringParserConstants {
    public static class SymbolInfo {
        String name;
        String type; // "ESTADO" o "SÍMBOLO"
        public boolean isInitial = false;
        public boolean isFinal = false;
        public boolean isBlank = false;

        public SymbolInfo(String name, String type) {
            this.name = name;
            this.type = type;
        }
    }

    public static class Instruction {
        String op;    // READ, WRITE, MOVE, GOTO, LABEL
        String arg1;  // Símbolo o Dirección
        String arg2;  // Condición (Símbolo leído)
        String state; // Estado actual

        public Instruction(String op, String arg1, String arg2, String state) {
            this.op = op;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.state = state;
        }

        @Override
        public String toString() {
            // Formato: OPERADOR arg1 arg2 state
            return String.format("%-8s %-6s %-6s %-6s", op, arg1, arg2, state);
        }
    }

    public Map<String, SymbolInfo> symbolTable = new LinkedHashMap<>();
    public List<CompilerError> errors = new ArrayList<>();
    public List<CompilerWarning> warnings = new ArrayList<>();
    public Set<String> definedStateBlocks = new HashSet<>();
    public Set<String> definedTransitions = new HashSet<>();
    public List<Instruction> intermediateCode = new ArrayList<>();

    private void registerSymbol(Token t, String type) {
        if (symbolTable.containsKey(t.image)) {
            reportError("Sem\u00e1ntico", "El identificador '" + t.image + "' ya fue declarado previamente como " + symbolTable.get(t.image).type + ". Consejo: Usa nombres \u00fanicos para cada entidad.", t);
        } else {
            symbolTable.put(t.image, new SymbolInfo(t.image, type));
        }
    }

    public void printSymbolTable() {
        System.out.println("\n------------------------------------------------------------");
        System.out.println("              TABLA DE S\u00cdMBOLOS (Turing Machine)");
        System.out.println("------------------------------------------------------------");
        System.out.printf("%-15s | %-10s | %-20s\n", "IDENTIFICADOR", "TIPO", "ATRIBUTOS");
        System.out.println("------------------------------------------------------------");
        for (SymbolInfo info : symbolTable.values()) {
            List<String> attrs = new ArrayList<>();
            if (info.isInitial) attrs.add("INICIAL");
            if (info.isFinal) attrs.add("FINAL");
            if (info.isBlank) attrs.add("BLANCO");
            String attrStr = attrs.isEmpty() ? "-" : attrs.toString();
            System.out.printf("%-15s | %-10s | %-20s\n", info.name, info.type, attrStr);
        }
        System.out.println("------------------------------------------------------------");
    }

    private void emit(String op, String a1, String a2, String s) {
        intermediateCode.add(new Instruction(op, a1, a2, s));
    }

    public static class CompilerError {
        String type;
        String message;
        int line;
        int column;

        public CompilerError(String type, String message, int line, int column) {
            this.type = type;
            this.message = message;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            // Se ajustó la puntuación para coincidir con tu formato exacto
            return "Error " + type + " en " + line + "," + column + ". " + message;
        }
    }

    private void reportError(String type, String message, Token t) {
        errors.add(new CompilerError(type, message, t.beginLine, t.beginColumn));
    }

    public static class CompilerWarning {
        String type;
        String message;
        int line;
        int column;

        public CompilerWarning(String type, String message, int line, int column) {
            this.type = type;
            this.message = message;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            return "Advertencia en " + line + "," + column + ". " + message;
        }
    }

    private void reportWarning(String type, String message, Token t) {
        warnings.add(new CompilerWarning(type, message, t.beginLine, t.beginColumn));
    }

    public void saveICGToFile(String filename) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {
            for (Instruction ins : intermediateCode) {
                writer.println(ins);
            }
            System.out.println("\u2714 Archivo de c\u00f3digo intermedio generado: " + filename);
        } catch (IOException e) {
            System.err.println("Error al escribir el archivo .tir: " + e.getMessage());
        }
    }

    private static void showHelp() {
        System.out.println("USO: java TuringParser <archivo.tm> [opciones]");
        System.out.println("\nOPCIONES:");
        System.out.println("  -o <nombre>   Especificar nombre del archivo de salida.");
        System.out.println("  -tir          Generar c\u00f3digo intermedio (.tir)");
        System.out.println("  -S            Generar c\u00f3digo ensamblador (.asm)");
        System.out.println("  -st           Mostrar tabla de s\u00edmbolos en consola.");
        System.out.println("  -O1           Activar optimizaci\u00f3n b\u00e1sica.");
        System.out.println("  -v, --version Mostrar versi\u00f3n.");
        System.out.println("  -h, --help    Mostrar esta ayuda.");
    }

    public static void main(String[] args) {
        String inputFile = null;
        String outputFile = null;
        boolean emitTir = false;
        boolean emitAsm = false;
        boolean showST = false;
        int optLevel = 0;

        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "-h": case "--help":
                    showHelp(); return;
                case "-v": case "--version":
                    System.out.println("TuringMachine Compiler (TMC) v0.1.1-alpha");
                    System.out.println("Marzo 2026");
                    return;
                case "-tir":
                    emitTir = true; break;
                case "-S":
                    emitAsm = true; break;
                case "-st":
                    showST = true; break;
                case "-O1":
                    optLevel = 1; break;
                case "-o":
                    if (i + 1 < args.length) outputFile = args[++i];
                    break;
                default:
                    if (!args[i].startsWith("-")) inputFile = args[i];
                    break;
            }
        }

        if (inputFile == null) {
            System.out.println("Error: No se especific\u00f3 archivo de entrada. Usa -h para ayuda.");
            return;
        }

        try {
            TuringParser parser = new TuringParser(new java.io.FileInputStream(inputFile));
            parser.Program();

            if (parser.errors.isEmpty()) {
                System.out.println("\u2714 COMPILACI\u00d3N EXITOSA (0 errores)");

                if (showST) parser.printSymbolTable();

                if (optLevel > 0) {
                    // Aquí llamaríamos a tu futuro optimizador
                    System.out.println("\u26a1 Aplicando optimizaci\u00f3n nivel " + optLevel + "...");
                    // parser.optimize(optLevel);
                }

                if (emitTir) {
                    String name = (outputFile != null) ? outputFile + ".tir" : inputFile.replace(".mt", ".tir");
                    parser.saveICGToFile(name);
                }

                if (emitAsm) {
                    System.out.println("\u2699 Generando ensamblador... (Fase Back-end)");
                    // parser.generateAssembly(outputFile);
                }
            } else {
                System.out.println("\u2716 SE ENCONTRARON " + parser.errors.size() + " ERRORES:");
                for (CompilerError e : parser.errors) {
                    System.out.println(e);
                }
            }

            if (! parser.warnings.isEmpty()) {
                System.out.println("\n--------------------------------");
                System.out.println("SE ENCONTRARON " + parser.warnings.size() + " ADVERTENCIAS:");
                for (CompilerWarning e : parser.warnings) {
                    System.out.println(e);
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /* ================= RECUPERACIÓN ================= */

    void recover(int... syncTokens) {
        Token t = getToken(1);

        if (t.kind == EOF || isKind(t.kind, syncTokens)) return;

        while (true) {
            getNextToken();
            t = getToken(1);
            if (t.kind == EOF || isKind(t.kind, syncTokens)) break;
        }
    }

    boolean isKind(int kind, int[] kinds) {
        for (int k : kinds) if (k == kind) return true;
        return false;
    }

    void error_skip_config() {
        Token t = getToken(1);

        while (t.kind != EOF &&
               t.kind != STATES &&
               t.kind != SYMBOLS &&
               t.kind != START &&
               t.kind != BLANK &&
               t.kind != FINALS &&
               t.kind != RBRACE) {

            getNextToken();
            t = getToken(1);
        }
    }

/* ================= SINTÁCTICO ================= */
  final public 
void Program() throws ParseException {
    try {
      jj_consume_token(MACHINE);
      jj_consume_token(NAME);
      jj_consume_token(COLON);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Se esperaba la palabra reservada \"machine\" seguida de un nombre (ID) seguido de '{'.",
                t
            );
        }

        recover(CONFIG, STATE);
    }
    ConfigBlock();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STATE:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      StateBlock();
    }
    try {
      jj_consume_token(END);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Cierra la declaraci\u00f3n con la palabra reservada 'end'",
                t
            );
        }
    }
    jj_consume_token(0);
}

  final public void ConfigBlock() throws ParseException {
    try {
      jj_consume_token(CONFIG);
      jj_consume_token(LBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar el bloque de definici\u00f3n. Se esperaba la palabra reservada \"config\" seguido de {",
                t
            );
        }

        recover(STATES, SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }
    ConfigEntry();
    try {
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado en la declaraci\u00f3n. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Error al declarar la m\u00e1quina. Necesitas cerrar el bloque con \"}\"",
                t
            );
        }

        recover(STATE, END);
    }
}

  final public void ConfigEntry() throws ParseException {Token t;
    try {
      jj_consume_token(STATES);
      jj_consume_token(COLON);
      IdList("ESTADO");
      jj_consume_token(COMMA);
    } catch (ParseException e) {
t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba una declaraci\u00f3n de los estados de la maquina. Revisa la sintaxis",
                t
            );
        }

        recover(SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(SYMBOLS);
      jj_consume_token(COLON);
      SymbolsList("SIMBOLO");
      jj_consume_token(COMMA);
    } catch (ParseException e) {
t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba una declaraci\u00f3n de los simbolos de cinta. Revisa la sintaxis",
                t
            );
        }

        recover(START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(START);
      jj_consume_token(COLON);
      t = jj_consume_token(ID);
      jj_consume_token(COMMA);
if (!symbolTable.containsKey(t.image)) {
                  reportError("Sem\u00e1ntico", "El estado inicial '" + t.image + "' no ha sido declarado en la lista 'states'. Consejo: Decl\u00e1ralo primero en [].", t);
            } else {
                symbolTable.get(t.image).isInitial = true;
            }
    } catch (ParseException e) {
t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n del estado inicial. Revisa la sintaxis",
                t
            );
        }

        recover(BLANK, FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(BLANK);
      jj_consume_token(COLON);
      t = jj_consume_token(SYMBOL);
      jj_consume_token(COMMA);
if (!symbolTable.containsKey(t.image)) {
                reportError("Sem\u00e1ntico", "El s\u00edmbolo blanco '" + t.image + "' no existe en 'symbols'. Consejo: Agr\u00e9galo a la lista de s\u00edmbolos permitidos.", t);
            } else {
                symbolTable.get(t.image).isBlank = true;
            }
    } catch (ParseException e) {
t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n del simbolo blanco. Revisa la sintaxis",
                t
            );
        }

        recover(FINALS, RBRACE, STATE, END);
    }
    try {
      jj_consume_token(FINALS);
      jj_consume_token(COLON);
      FinalIdList();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
    } catch (ParseException e) {
t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "L\u00e9xico",
            "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n de los estados finales. Revisa la sintaxis",
                t
            );
        }

        recover(RBRACE, STATE, END);
    }
}

  final public void StateBlock() throws ParseException {Token stateToken;
    try {
      jj_consume_token(STATE);
      stateToken = jj_consume_token(ID);
if (!symbolTable.containsKey(stateToken.image)) {
                    reportError("Sem\u00e1ntico", "El estado '" + stateToken.image + "' no est\u00e1 declarado en 'states'.", stateToken);
                } else if (symbolTable.get(stateToken.image).isFinal) {
                    reportWarning("Sem\u00e1ntico", "El estado '" + stateToken.image + "' es final y no deber\u00eda tener transiciones.", stateToken);
                }

                if (definedStateBlocks.contains(stateToken.image)) {
                    reportWarning(
                        "Sem\u00e1ntico",
                        "El estado '" + stateToken.image + "' ya tiene un bloque definido previamente. Consejo: Agrupa todas las transiciones ('on ...') de este estado en un solo bloque.",
                        stateToken
                    );
                } else {
                    definedStateBlocks.add(stateToken.image);
                }

                emit("LABEL", stateToken.image, "-", "-");
      jj_consume_token(PRODUCE);
      label_2:
      while (true) {
        TransitionBlock(stateToken.image);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ON:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1lido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la declaraci\u00f3n de transici\u00f3n. Usa la palabra reservada 'state' y el identificador adecuado",
                t
            );
        }

        recover(STATE, END);
    }
}

  final public void TransitionBlock(String currentState) throws ParseException {Token readSym, writeSym, dirToken, nextState;
    try {
      jj_consume_token(ON);
      readSym = jj_consume_token(SYMBOL);
      jj_consume_token(COLON);
      jj_consume_token(LBRACE);
      jj_consume_token(WRITE);
      jj_consume_token(COLON);
      writeSym = jj_consume_token(SYMBOL);
      jj_consume_token(COMMA);
      jj_consume_token(MOVE);
      jj_consume_token(COLON);
      dirToken = jj_consume_token(DIR);
      jj_consume_token(COMMA);
      jj_consume_token(NEXT);
      jj_consume_token(COLON);
      nextState = jj_consume_token(ID);
if (!symbolTable.containsKey(readSym.image)) {
                    reportError("Sem\u00e1ntico", "El s\u00edmbolo a leer '" + readSym.image + "' no existe en 'symbols'.", readSym);
                }

                String transitionSignature = currentState + "-" + readSym.image;
                if (definedTransitions.contains(transitionSignature)) {
                    reportError("Sem\u00e1ntico", "Ambig\u00fcedad detectada (No determinismo). El estado '" + currentState + "' ya tiene una acci\u00f3n definida cuando lee el s\u00edmbolo '" + readSym.image + "'.", readSym);
                } else {
                    definedTransitions.add(transitionSignature);
                }

                if (!symbolTable.containsKey(writeSym.image)) {
                    reportError("Sem\u00e1ntico", "El s\u00edmbolo a escribir '" + writeSym.image + "' no existe en 'symbols'.", writeSym);
                }

                if (!symbolTable.containsKey(nextState.image)) {
                    reportError("Sem\u00e1ntico", "El estado de destino '" + nextState.image + "' no est\u00e1 declarado.", nextState);
                }

                String cond = readSym.image;

                emit("READ",  cond,           "-",  currentState);
                emit("PUT",   writeSym.image, cond, currentState);
                emit("MOV",   dirToken.image, cond, currentState);
                emit("GOTO",  nextState.image,cond, currentState);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        jj_consume_token(COMMA);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "L\u00e9xico",
                "Car\u00e1cter inv\u00e1ido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, n\u00fameros y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sint\u00e1ctico",
                "Se esperaba la transici\u00f3n. Revisa la documentaci\u00f3n",
                t
            );
        }

        recover(SEMICOLON, END);
    }
}

  final public void IdList(String type) throws ParseException {Token t;
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      t = jj_consume_token(ID);
registerSymbol(t, type);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        t = jj_consume_token(ID);
registerSymbol(t, type);
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
}

  final public void SymbolsList(String type) throws ParseException {Token t;
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYMBOL:{
      t = jj_consume_token(SYMBOL);
registerSymbol(t, type);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        t = jj_consume_token(SYMBOL);
registerSymbol(t, type);
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
}

// Especial para marcar estados finales
  final public void FinalIdList() throws ParseException {Token t;
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      t = jj_consume_token(ID);
if (symbolTable.containsKey(t.image)) {
                symbolTable.get(t.image).isFinal = true;
            } else {
                reportError("Sem\u00e1ntico", "El estado final '" + t.image + "' no fue declarado en 'states'.", t);
            }
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        t = jj_consume_token(ID);
if (symbolTable.containsKey(t.image)) {
                symbolTable.get(t.image).isFinal = true;
            } else {
                reportError("Sem\u00e1ntico", "El estado final '" + t.image + "' no fue declarado en 'states'.", t);
            }
      }
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
}

  /** Generated Token Manager. */
  public TuringParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[10];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2000,0x2000000,0x4000,0x2000000,0x2000000,0x20000000,0x2000000,0x100000,0x2000000,0x20000000,};
	}

  /** Constructor with InputStream. */
  public TuringParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TuringParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new TuringParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TuringParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new TuringParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new TuringParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TuringParser(TuringParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TuringParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[32];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 10; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 32; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
