options {
    STATIC = false;
    DEBUG_PARSER = false;
}

PARSER_BEGIN(TuringParser)
import java.util.*;
import java.io.*;

public class TuringParser {
    int globalTransCounter = 0;

    public static class SymbolInfo {
        String name;
        String type; // "ESTADO" o "SÍMBOLO"
        public boolean isInitial = false;
        public boolean isFinal = false;
        public boolean isBlank = false;

        public SymbolInfo(String name, String type) {
            this.name = name;
            this.type = type;
        }
    }

    public static class Instruction {
        String op;    // READ, WRITE, MOVE, GOTO, LABEL
        String arg1;  // Símbolo o Dirección
        String arg2;  // Condición (Símbolo leído)
        String state; // Estado actual
        int transId;

        public Instruction(String op, String arg1, String arg2, String state, int transId) {
            this.op = op;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.state = state;
            this.transId = transId;
        }

        @Override
        public String toString() {
            // Formato: OPERADOR arg1 arg2 state
            return String.format("%-8s %-6s %-6s %-6s", op, arg1, arg2, state);
        }
    }

    public Map<String, SymbolInfo> symbolTable = new LinkedHashMap<>();
    public List<CompilerError> errors = new ArrayList<>();
    public List<CompilerWarning> warnings = new ArrayList<>();
    public Set<String> definedStateBlocks = new HashSet<>();
    public Set<String> definedTransitions = new HashSet<>();
    public List<Instruction> intermediateCode = new ArrayList<>();

    private void registerSymbol(Token t, String type) {
        if (symbolTable.containsKey(t.image)) {
            reportError("Semántico", "El identificador '" + t.image + "' ya fue declarado previamente como " + symbolTable.get(t.image).type + ". Consejo: Usa nombres únicos para cada entidad.", t);
        } else {
            symbolTable.put(t.image, new SymbolInfo(t.image, type));
        }
    }

    public void printSymbolTable() {
        System.out.println("\n------------------------------------------------------------");
        System.out.println("              TABLA DE SÍMBOLOS (Turing Machine)");
        System.out.println("------------------------------------------------------------");
        System.out.printf("%-15s | %-10s | %-20s\n", "IDENTIFICADOR", "TIPO", "ATRIBUTOS");
        System.out.println("------------------------------------------------------------");
        for (SymbolInfo info : symbolTable.values()) {
            List<String> attrs = new ArrayList<>();
            if (info.isInitial) attrs.add("INICIAL");
            if (info.isFinal) attrs.add("FINAL");
            if (info.isBlank) attrs.add("BLANCO");
            String attrStr = attrs.isEmpty() ? "-" : attrs.toString();
            System.out.printf("%-15s | %-10s | %-20s\n", info.name, info.type, attrStr);
        }
        System.out.println("------------------------------------------------------------");
    }

    private void emit(String op, String a1, String a2, String s) {
        intermediateCode.add(new Instruction(op, a1, a2, s, globalTransCounter));
    }

    public static class CompilerError {
        String type;
        String message;
        int line;
        int column;

        public CompilerError(String type, String message, int line, int column) {
            this.type = type;
            this.message = message;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            // Se ajustó la puntuación para coincidir con tu formato exacto
            return "Error " + type + " en " + line + "," + column + ". " + message;
        }
    }

    private void reportError(String type, String message, Token t) {
        errors.add(new CompilerError(type, message, t.beginLine, t.beginColumn));
    }

    public static class CompilerWarning {
        String type;
        String message;
        int line;
        int column;

        public CompilerWarning(String type, String message, int line, int column) {
            this.type = type;
            this.message = message;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            return "Advertencia en " + line + "," + column + ". " + message;
        }
    }

    private void reportWarning(String type, String message, Token t) {
        warnings.add(new CompilerWarning(type, message, t.beginLine, t.beginColumn));
    }

    public void optimize(int level) {
        if (level <= 0) return;

        if (level >= 1) {
            List<Instruction> optimized = new ArrayList<>();
            for (Instruction ins : intermediateCode) {
                // Regla: No escribir si es el mismo símbolo que leímos
                if (ins.op.equals("PUT") && ins.arg1.equals(ins.arg2)) continue;

                // Regla: No mover si la dirección es S (Stay)
                if (ins.op.equals("MOV") && ins.arg1.equals("S")) continue;

                optimized.add(ins);
            }
            this.intermediateCode = optimized;
        }

        if (level >= 2) {
            Set<String> reachedStates = new HashSet<>();

            for(SymbolInfo s : symbolTable.values()) if(s.isInitial) reachedStates.add(s.name);

            for (Instruction ins : intermediateCode) {
                if (ins.op.equals("GOTO")) reachedStates.add(ins.arg1);
            }

            List<Instruction> optimized = new ArrayList<>();
            boolean skipping = false;

            for (Instruction ins : intermediateCode) {
                if (ins.op.equals("LABEL")) {
                    skipping = !reachedStates.contains(ins.arg1);
                }
                if (!skipping) optimized.add(ins);
            }
            this.intermediateCode = optimized;
        }
        System.out.println("Optimización -O" + level + " completada.");
    }

    public void saveICGToFile(String filename) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {
            for (Instruction ins : intermediateCode) {
                writer.println(ins);
            }
            System.out.println("✔ Archivo de código intermedio generado: " + filename);
        } catch (IOException e) {
            System.err.println("Error al escribir el archivo .tir: " + e.getMessage());
        }
    }

    public void generateLogicAsm(String outputFile) {
        if (outputFile == null) outputFile = "logic.asm";

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            char blankChar = 'B';
            for (SymbolInfo info : symbolTable.values()) {
                if (info.isBlank) {
                    blankChar = info.name.charAt(0);
                    break;
                }
            }

            // --- CABECERA PARA GNU AS (Sintaxis Intel) ---
            writer.println(".intel_syntax noprefix"); // <--- CRITICO: Permite sintaxis Intel en 'as'
            writer.println(".section .text");
            writer.println(".global run_turing_logic");
            writer.println(".extern step_counter, max_steps, current_state_is_final, blank_symbol");

            writer.println("\nrun_turing_logic:");
            writer.println("    push rbx");
            writer.println("    mov rbx, rdi");

            // Usamos la sintaxis de direccionamiento compatible con 'as'
            writer.println("    lea rax, [rip + blank_symbol]");
            writer.println("    mov byte ptr [rax], " + (int)blankChar);

            boolean isFirstLabel = true;

            for (Instruction ins : intermediateCode) {
                switch (ins.op) {
                    case "LABEL":
                        if (!isFirstLabel) {
                            writer.println("    mov rax, -2");
                            writer.println("    jmp exit_logic");
                        }
                        isFirstLabel = false;

                        writer.println("\nstate_" + ins.arg1 + ":");
                        // CAMBIO: [rel ...] por [rip + ...]
                        writer.println("    mov byte ptr [rip + current_state_is_final], " + (symbolTable.get(ins.arg1).isFinal ? "1" : "0"));
                        break;

                    case "READ":
                        // CAMBIO: Añadimos 'ptr' y usamos [rip + ...]
                        writer.println("    inc qword ptr [rip + step_counter]");
                        writer.println("    mov rax, [rip + step_counter]");
                        writer.println("    cmp rax, [rip + max_steps]");
                        writer.println("    jg  exit_limit");

                        writer.println("    cmp byte ptr [rbx], '" + ins.arg1 + "'");
                        writer.println("    jne fallback_trans_" + ins.transId);
                        break;

                    case "PUT":
                        writer.println("    mov byte ptr [rbx], '" + ins.arg1 + "'");
                        break;

                    case "MOV":
                        if (ins.arg1.equals("R")) writer.println("    inc rbx");
                        else if (ins.arg1.equals("L")) writer.println("    dec rbx");
                        break;

                    case "GOTO":
                        writer.println("    jmp state_" + ins.arg1);
                        writer.println("    fallback_trans_" + ins.transId + ":");
                        break;
                }
            }

            if (!isFirstLabel) {
                writer.println("    mov rax, -2 # Codigo de error: Transicion no definida (Rechazo)");
                writer.println("    jmp exit_logic");
            }

            for (SymbolInfo info : symbolTable.values()) {
                if (info.type.equals("ESTADO") && !definedStateBlocks.contains(info.name)) {
                    writer.println("\nstate_" + info.name + ":");
                    // USA ESTA LÍNEA:
                    writer.println("    mov byte ptr [rip + current_state_is_final], " + (info.isFinal ? "1" : "0"));
                    writer.println("    jmp exit_logic");
                }
            }

            writer.println("\nexit_logic:");
            writer.println("    pop rbx");
            writer.println("    ret");

            writer.println("\nexit_limit:");
            // CAMBIO: Eliminamos acentos para evitar el error 0xc3
            writer.println("    mov rax, -1");
            writer.println("    jmp exit_logic");

            System.out.println("Archivo logic.asm generado con éxito.");
        } catch (IOException e) {
            System.err.println("Error generando logic.asm: " + e.getMessage());
        }
    }

    private static void showHelp() {
        System.out.println("USO: java TuringParser <archivo.tm> [opciones]");
        System.out.println("\nOPCIONES:");
        System.out.println("  -o <nombre>   Especificar nombre del archivo de salida.");
        System.out.println("  -tir          Generar código intermedio (.tir)");
        System.out.println("  -S            Generar código ensamblador (.asm)");
        System.out.println("  -st           Mostrar tabla de símbolos en consola.");
        System.out.println("  -O1           Optimización de mirilla");
        System.out.println("  -O2           Optimización de flujo");
        System.out.println("  -v, --version Mostrar versión.");
        System.out.println("  -h, --help    Mostrar esta ayuda.");
        System.out.println("  -?            Muestra ayuda");
    }

    private File extractRuntime() throws IOException {
        File tempRuntime = File.createTempFile("tm_runtime", ".o");
        tempRuntime.deleteOnExit();

        // Busca el archivo 'runtime.o' dentro de los recursos del JAR
        try (InputStream is = getClass().getResourceAsStream("/resources/runtime.o");
             OutputStream os = new FileOutputStream(tempRuntime)) {
            if (is == null) throw new IOException("No se encontró el motor (runtime.o) en los recursos.");
            byte[] buffer = new byte[1024];
            int bytesRead;
            while ((bytesRead = is.read(buffer)) != -1) {
                os.write(buffer, 0, bytesRead);
            }
        }
        return tempRuntime;
    }

    private void buildBinary(String asmFileName, String finalOutputName) {
        try {
            System.out.println("🔨 Ensamblando y enlazando...");

            // 1. Extraer el runtime.o que incluimos en el binario
            File runtimeO = extractRuntime();

            // 2. Ejecutar 'as' (Ensamblador del sistema)
            String objFile = asmFileName.replace(".asm", ".o");
            Process as = new ProcessBuilder("as", "--64", asmFileName, "-o", objFile).inheritIO().start();
            if (as.waitFor() != 0) throw new Exception("Error en el ensamblado.");

            // 3. Ejecutar 'ld' (Enlazador del sistema)
            Process ld = new ProcessBuilder("ld", runtimeO.getAbsolutePath(), objFile, "-o", finalOutputName).inheritIO().start();
            if (ld.waitFor() != 0) throw new Exception("Error en el enlazado.");

            // Limpieza de archivos temporales
            new File(asmFileName).delete();
            new File(objFile).delete();

            System.out.println("🚀 ¡Listo! Binario creado: " + finalOutputName);

        } catch (Exception e) {
            System.err.println("❌ Error crítico al crear el ejecutable: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        String inputFile = null;
        String outputFile = null;
        boolean emitTir = false;
        boolean emitAsm = false;
        boolean showST = false;
        int optLevel = 0;

        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "-h": case "-?": case "--help":
                    showHelp(); return;
                case "-v": case "--version":
                    System.out.println("TuringMachine Compiler (TMC) v1.0.0-beta");
                    System.out.println("Abril 2026");
                    return;
                case "-tir":
                    emitTir = true; break;
                case "-S":
                    emitAsm = true; break;
                case "-st":
                    showST = true; break;
                case "-O1":
                    optLevel = 1; break;
                case "-O2":
                    optLevel = 2; break;
                case "-o":
                    if (i + 1 < args.length) outputFile = args[++i];
                    break;
                default:
                    if (!args[i].startsWith("-")) inputFile = args[i];
                    break;
            }
        }

        if (inputFile == null) {
            System.out.println("Error: No se especificó archivo de entrada. Usa -h para ayuda.");
            return;
        }

        try {
            TuringParser parser = new TuringParser(new java.io.FileInputStream(inputFile));
            parser.Program();

            if (parser.errors.isEmpty()) {
                System.out.println("✔ COMPILACIÓN EXITOSA (0 errores)");

                if (showST) parser.printSymbolTable();

                if (optLevel > 0) {
                    parser.optimize(optLevel);
                }

                if (emitTir) {
                    String name = (outputFile != null) ? outputFile + ".tir" : inputFile.replace(".mt", ".tir");
                    parser.saveICGToFile(name);
                }

                if (emitAsm) {
                    System.out.println("Generando back-end x86_64...");
                    String asmName = (outputFile != null) ? outputFile + ".asm" : "logic.asm";
                    parser.generateLogicAsm(asmName);
                }

                if (!emitTir && !emitAsm) {
                    // Comportamiento por defecto: Crear ejecutable final
                    String asmName = "temp_logic.asm";
                    String binName = (outputFile != null) ? outputFile : "a.out"; // a.out es el estándar en Linux

                    // 1. Generamos el .asm temporal
                    parser.generateLogicAsm(asmName);

                    // 2. Ensamblamos, enlazamos y borramos los temporales
                    parser.buildBinary(asmName, binName);
                }
            } else {
                System.out.println("✖ SE ENCONTRARON " + parser.errors.size() + " ERRORES:");
                for (CompilerError e : parser.errors) {
                    System.out.println(e);
                }
            }

            if (! parser.warnings.isEmpty()) {
                System.out.println("\n--------------------------------");
                System.out.println("SE ENCONTRARON " + parser.warnings.size() + " ADVERTENCIAS:");
                for (CompilerWarning e : parser.warnings) {
                    System.out.println(e);
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /* ================= RECUPERACIÓN ================= */

    void recover(int... syncTokens) {
        Token t = getToken(1);

        if (t.kind == EOF || isKind(t.kind, syncTokens)) return;

        while (true) {
            getNextToken();
            t = getToken(1);
            if (t.kind == EOF || isKind(t.kind, syncTokens)) break;
        }
    }

    boolean isKind(int kind, int[] kinds) {
        for (int k : kinds) if (k == kind) return true;
        return false;
    }

    void error_skip_config() {
        Token t = getToken(1);

        while (t.kind != EOF &&
               t.kind != STATES &&
               t.kind != SYMBOLS &&
               t.kind != START &&
               t.kind != BLANK &&
               t.kind != FINALS &&
               t.kind != RBRACE) {

            getNextToken();
            t = getToken(1);
        }
    }
}
PARSER_END(TuringParser)

/* ================= LÉXICO ================= */

SKIP : {
    " " | "\t" | "\r" | "\n"
  | <"//" (~["\n","\r"])* ("\n"|"\r"|"\r\n")>
}

TOKEN : {
    < MACHINE: "machine" >
  | < CONFIG: "config" >
  | < STATES: "states" >
  | < SYMBOLS: "symbols" >
  | < START: "start" >
  | < BLANK: "blank" >
  | < FINALS: "finals" >
  | < STATE: "state" >
  | < ON: "on" >
  | < WRITE: "write" >
  | < MOVE: "move" >
  | < NEXT: "next" >
  | < END: "end" >
}

TOKEN : { < DIR: "R" | "L" | "S" > }
TOKEN : { < SYMBOL: "0" | "1" | ["A"-"Z"] > }

TOKEN : {
    < LBRACE: "{" > | < RBRACE: "}" >
  | < LBRACKET: "[" > | < RBRACKET: "]" >
  | < COMMA: "," > | < COLON: ":" >
  | < PRODUCE: "->"> | <SEMICOLON: ";">
}

TOKEN : { < ID: ["a"-"z"] (["a"-"z","0"-"9","_"])* > }
TOKEN : { < NAME: ["a"-"z","A"-"Z"] (["a"-"z","A"-"Z","0"-"9","_"])*> }

// Token comodín para atrapar errores léxicos
TOKEN : { < UNEXPECTED_CHAR: ~[] > }

/* ================= SINTÁCTICO ================= */

void Program() : {}
{
    try {
        <MACHINE>
        <NAME>
        <COLON>
    } catch (ParseException e) {
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "Léxico",
                "Carácter inválido '" + t.image + "' encontrado en la declaración. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sintáctico",
                "Error al declarar la máquina. Se esperaba la palabra reservada \"machine\" seguida de un nombre (ID) seguido de '{'.",
                t
            );
        }

        recover(CONFIG, STATE);
    }

    ConfigBlock()

    (
        StateBlock()
    )*

    try { <END> } catch (ParseException e) {
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "Léxico",
                "Carácter inválido '" + t.image + "' encontrado en la declaración. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sintáctico",
                "Error al declarar la máquina. Cierra la declaración con la palabra reservada 'end'",
                t
            );
        }
    }
    <EOF>
}

void ConfigBlock() : {}
{
    try {
        <CONFIG> <LBRACE>
    } catch (ParseException e){
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado en la declaración. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Error al declarar el bloque de definición. Se esperaba la palabra reservada \"config\" seguido de {",
                t
            );
        }

        recover(STATES, SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }

    ConfigEntry()

    try {
        <RBRACE>
    } catch (ParseException e) {
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado en la declaración. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Error al declarar la máquina. Necesitas cerrar el bloque con \"}\"",
                t
            );
        }

        recover(STATE, END);
    }
}

void ConfigEntry() : { Token t; }
{
    try { <STATES> <COLON> IdList("ESTADO") <COMMA> } catch (ParseException e) {
        t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba una declaración de los estados de la maquina. Revisa la sintaxis",
                t
            );
        }

        recover(SYMBOLS, START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try { <SYMBOLS> <COLON> SymbolsList("SIMBOLO") <COMMA> } catch (ParseException e) {
        t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba una declaración de los simbolos de cinta. Revisa la sintaxis",
                t
            );
        }

        recover(START, BLANK, FINALS, RBRACE, STATE, END);
    }
    try { <START> <COLON> t=<ID> <COMMA> {
            if (!symbolTable.containsKey(t.image)) {
                  reportError("Semántico", "El estado inicial '" + t.image + "' no ha sido declarado en la lista 'states'. Consejo: Decláralo primero en [].", t);
            } else {
                symbolTable.get(t.image).isInitial = true;
            }
        }
    } catch (ParseException e) {
        t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba la declaración del estado inicial. Revisa la sintaxis",
                t
            );
        }

        recover(BLANK, FINALS, RBRACE, STATE, END);
    }
    try { <BLANK> <COLON> t=<SYMBOL> <COMMA> {
            if (!symbolTable.containsKey(t.image)) {
                reportError("Semántico", "El símbolo blanco '" + t.image + "' no existe en 'symbols'. Consejo: Agrégalo a la lista de símbolos permitidos.", t);
            } else {
                symbolTable.get(t.image).isBlank = true;
            }
        }
    } catch (ParseException e) {
        t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba la declaración del simbolo blanco. Revisa la sintaxis",
                t
            );
        }

        recover(FINALS, RBRACE, STATE, END);
    }
    try { <FINALS> <COLON> FinalIdList() (<COMMA>)? } catch (ParseException e) {
        t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
        reportError(
            "Léxico",
            "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
            t
        );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba la declaración de los estados finales. Revisa la sintaxis",
                t
            );
        }

        recover(RBRACE, STATE, END);
    }
}

void StateBlock() : { Token stateToken; }
{
    try {
            <STATE> stateToken=<ID> {
                if (!symbolTable.containsKey(stateToken.image)) {
                    reportError("Semántico", "El estado '" + stateToken.image + "' no está declarado en 'states'.", stateToken);
                } else if (symbolTable.get(stateToken.image).isFinal) {
                    reportWarning("Semántico", "El estado '" + stateToken.image + "' es final y no debería tener transiciones.", stateToken);
                }

                if (definedStateBlocks.contains(stateToken.image)) {
                    reportWarning(
                        "Semántico",
                        "El estado '" + stateToken.image + "' ya tiene un bloque definido previamente. Consejo: Agrupa todas las transiciones ('on ...') de este estado en un solo bloque.",
                        stateToken
                    );
                } else {
                    definedStateBlocks.add(stateToken.image);
                }

                emit("LABEL", stateToken.image, "-", "-");
            }
            <PRODUCE>
            (TransitionBlock(stateToken.image))+
            <SEMICOLON>
    } catch (ParseException e) {
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "Léxico",
                "Carácter inválido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba la declaración de transición. Usa la palabra reservada 'state' y el identificador adecuado",
                t
            );
        }

        recover(STATE, END);
    }
}

void TransitionBlock(String currentState) : { Token readSym, writeSym, dirToken, nextState; }
{
    try {
            <ON> readSym=<SYMBOL> <COLON> <LBRACE>
            {
                globalTransCounter++;
            }
            <WRITE> <COLON> writeSym=<SYMBOL> <COMMA>
            <MOVE> <COLON> dirToken=<DIR> <COMMA>
            <NEXT> <COLON> nextState=<ID>

            {
                if (!symbolTable.containsKey(readSym.image)) {
                    reportError("Semántico", "El símbolo a leer '" + readSym.image + "' no existe en 'symbols'.", readSym);
                }

                String transitionSignature = currentState + "-" + readSym.image;
                if (definedTransitions.contains(transitionSignature)) {
                    reportError("Semántico", "Ambigüedad detectada (No determinismo). El estado '" + currentState + "' ya tiene una acción definida cuando lee el símbolo '" + readSym.image + "'.", readSym);
                } else {
                    definedTransitions.add(transitionSignature);
                }

                if (!symbolTable.containsKey(writeSym.image)) {
                    reportError("Semántico", "El símbolo a escribir '" + writeSym.image + "' no existe en 'symbols'.", writeSym);
                }

                if (!symbolTable.containsKey(nextState.image)) {
                    reportError("Semántico", "El estado de destino '" + nextState.image + "' no está declarado.", nextState);
                }

                String cond = readSym.image;

                emit("READ",  cond,           "-",  currentState);
                emit("PUT",   writeSym.image, cond, currentState);
                emit("MOV",   dirToken.image, cond, currentState);
                emit("GOTO",  nextState.image,cond, currentState);
            }

            (<COMMA>)? <RBRACE>
    } catch (ParseException e) {
        Token t = getToken(1);

        if (t.kind == UNEXPECTED_CHAR) {
            reportError(
                "Léxico",
                "Carácter inváido '" + t.image + "' encontrado. Consejo: Los nombres solo pueden contener letras, números y guiones bajos.",
                t
            );
        } else {
            reportError(
                "Sintáctico",
                "Se esperaba la transición. Revisa la documentación",
                t
            );
        }

        recover(SEMICOLON, END);
    }
}

void IdList(String type) : { Token t; }
{
    <LBRACKET>
    (
        t=<ID> { registerSymbol(t, type); }
        ( <COMMA> t=<ID> { registerSymbol(t, type); } )* )?
    <RBRACKET>
}

void SymbolsList(String type) : { Token t; }
{
    <LBRACKET>
    (
        t=<SYMBOL> { registerSymbol(t, type); }
        ( <COMMA> t=<SYMBOL> { registerSymbol(t, type); } )* )?
    <RBRACKET>
}

// Especial para marcar estados finales
void FinalIdList() : { Token t; }
{
    <LBRACKET>
    (
        t=<ID> {
            if (symbolTable.containsKey(t.image)) {
                symbolTable.get(t.image).isFinal = true;
            } else {
                reportError("Semántico", "El estado final '" + t.image + "' no fue declarado en 'states'.", t);
            }
        }
        ( <COMMA> t=<ID> {
             if (symbolTable.containsKey(t.image)) {
                symbolTable.get(t.image).isFinal = true;
            } else {
                reportError("Semántico", "El estado final '" + t.image + "' no fue declarado en 'states'.", t);
            }
        } )* )?
    <RBRACKET>
}